name: Build and Release C-Shell

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-latest
            args: "--target aarch64-apple-darwin"

          - platform: windows-latest
            args: ""

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Dependencies
        run: npm install

      - name: Build & Release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: "C-Shell ${{ github.ref_name }}"
          releaseBody: |
            ## C-Shell Beta

            Automatic build generated by GitHub Actions.

            ### Included
            - Windows Installer
            - macOS Installer

            Please report bugs through GitHub Issues.
          releaseDraft: false
          prerelease: true
          args: ${{ matrix.args }}
